---
!Config
emulate: True
instances:
    - !Instance
      name: "Bachman's Warbler"
      file: "data/bachman's-warbler.wav"
      pin: 24
      channel: 0
    - !Instance
      name: "Dusky Seaside Sparrow"
      file: "data/dusky-seaside-sparrow.wav"
      pin: 26
      channel: 1