---
!Config
instances:
    - !Instance
      name: "Bachman's Warbler"
      file: "data/bachman's-warbler.wav"
      input: 2 # MPR121 pin
      output: 0 # pygame mixer channel
    - !Instance
      name: "Dusky Seaside Sparrow"
      file: "data/dusky-seaside-sparrow.wav"
      input: 3
      output: 1
    - !Instance
      name: "Kaua`i `O`o"
      file: "data/kaua`i-`o`o.wav"
      input: 4
      output: 2