---
!Config
emulate: True
instances:
    - !Instance
      name: "Bachmans Warbler"
      file: "data/1.wav"
      pin: 24
    - !Instance
      name: "Passenger Pigeon"
      file: "data/2.wav"
      pin: 26